# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_export"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Export CLInvoice data to different file formats."

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice_export"

[dependencies]
clinvoice_finance = {branch = "release/0.3", git = "https://github.com/Iron-E/clinvoice_finance"}
clinvoice_schema = {branch = "release/0.8", git = "https://github.com/Iron-E/clinvoice_schema"}

[dev-dependencies]
pretty_assertions = "1"

[features]
default = ["markdown"]
markdown = []
